

services:
  messenger.api:
    image: ${DOCKER_REGISTRY-}messengerapi
    container_name: WS_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"